# Generated by Django 5.1.4 on 2025-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Prayer_requests",
            new_name="Prayer_request",
        ),
        migrations.DeleteModel(
            name="Events",
        ),
    ]
